/* tslint:disable */
/* eslint-disable */
/**
 * El Rastro
 * Grupo B7 - Ingeniería Web
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Mensaje
 */
export interface Mensaje {
    /**
     * 
     * @type {string}
     * @memberof Mensaje
     */
    idMensaje: string;
    /**
     * 
     * @type {string}
     * @memberof Mensaje
     */
    emisor: string;
    /**
     * 
     * @type {string}
     * @memberof Mensaje
     */
    receptor: string;
    /**
     * 
     * @type {string}
     * @memberof Mensaje
     */
    producto: string;
    /**
     * 
     * @type {string}
     * @memberof Mensaje
     */
    contenido: string;
    /**
     * 
     * @type {string}
     * @memberof Mensaje
     */
    fechaPublicacion: string;
}

/**
 * Check if a given object implements the Mensaje interface.
 */
export function instanceOfMensaje(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "idMensaje" in value;
    isInstance = isInstance && "emisor" in value;
    isInstance = isInstance && "receptor" in value;
    isInstance = isInstance && "producto" in value;
    isInstance = isInstance && "contenido" in value;
    isInstance = isInstance && "fechaPublicacion" in value;

    return isInstance;
}

export function MensajeFromJSON(json: any): Mensaje {
    return MensajeFromJSONTyped(json, false);
}

export function MensajeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mensaje {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idMensaje': json['idMensaje'],
        'emisor': json['emisor'],
        'receptor': json['receptor'],
        'producto': json['producto'],
        'contenido': json['contenido'],
        'fechaPublicacion': json['fecha_publicacion'],
    };
}

export function MensajeToJSON(value?: Mensaje | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idMensaje': value.idMensaje,
        'emisor': value.emisor,
        'receptor': value.receptor,
        'producto': value.producto,
        'contenido': value.contenido,
        'fecha_publicacion': value.fechaPublicacion,
    };
}

