/* tslint:disable */
/* eslint-disable */
/**
 * Jesus Antona
 * Ingeniería Web
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductoInput
 */
export interface ProductoInput {
    /**
     * 
     * @type {string}
     * @memberof ProductoInput
     */
    idProd: string;
    /**
     * 
     * @type {string}
     * @memberof ProductoInput
     */
    vendedor: string;
    /**
     * 
     * @type {string}
     * @memberof ProductoInput
     */
    titulo: string;
    /**
     * 
     * @type {string}
     * @memberof ProductoInput
     */
    descripcion: string;
    /**
     * 
     * @type {number}
     * @memberof ProductoInput
     */
    lat: number;
    /**
     * 
     * @type {number}
     * @memberof ProductoInput
     */
    _long: number;
    /**
     * 
     * @type {string}
     * @memberof ProductoInput
     */
    direccion: string;
    /**
     * 
     * @type {number}
     * @memberof ProductoInput
     */
    edad: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductoInput
     */
    precio: number;
    /**
     * 
     * @type {number}
     * @memberof ProductoInput
     */
    peso: number;
    /**
     * 
     * @type {string}
     * @memberof ProductoInput
     */
    fechaPublicacion: string;
    /**
     * 
     * @type {string}
     * @memberof ProductoInput
     */
    fechaCierre: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductoInput
     */
    pagado: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductoInput
     */
    valorado: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductoInput
     */
    imagenes?: Array<string> | null;
}

/**
 * Check if a given object implements the ProductoInput interface.
 */
export function instanceOfProductoInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "idProd" in value;
    isInstance = isInstance && "vendedor" in value;
    isInstance = isInstance && "titulo" in value;
    isInstance = isInstance && "descripcion" in value;
    isInstance = isInstance && "lat" in value;
    isInstance = isInstance && "_long" in value;
    isInstance = isInstance && "direccion" in value;
    isInstance = isInstance && "edad" in value;
    isInstance = isInstance && "precio" in value;
    isInstance = isInstance && "peso" in value;
    isInstance = isInstance && "fechaPublicacion" in value;
    isInstance = isInstance && "fechaCierre" in value;
    isInstance = isInstance && "pagado" in value;
    isInstance = isInstance && "valorado" in value;

    return isInstance;
}

export function ProductoInputFromJSON(json: any): ProductoInput {
    return ProductoInputFromJSONTyped(json, false);
}

export function ProductoInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductoInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idProd': json['idProd'],
        'vendedor': json['vendedor'],
        'titulo': json['titulo'],
        'descripcion': json['descripcion'],
        'lat': json['lat'],
        '_long': json['long'],
        'direccion': json['direccion'],
        'edad': json['edad'],
        'precio': json['precio'],
        'peso': json['peso'],
        'fechaPublicacion': json['fecha_publicacion'],
        'fechaCierre': json['fecha_cierre'],
        'pagado': json['pagado'],
        'valorado': json['valorado'],
        'imagenes': !exists(json, 'imagenes') ? undefined : json['imagenes'],
    };
}

export function ProductoInputToJSON(value?: ProductoInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idProd': value.idProd,
        'vendedor': value.vendedor,
        'titulo': value.titulo,
        'descripcion': value.descripcion,
        'lat': value.lat,
        'long': value._long,
        'direccion': value.direccion,
        'edad': value.edad,
        'precio': value.precio,
        'peso': value.peso,
        'fecha_publicacion': value.fechaPublicacion,
        'fecha_cierre': value.fechaCierre,
        'pagado': value.pagado,
        'valorado': value.valorado,
        'imagenes': value.imagenes,
    };
}

