/* tslint:disable */
/* eslint-disable */
/**
 * El Rastro
 * Grupo B7 - Ingeniería Web
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Puja
 */
export interface Puja {
    /**
     * 
     * @type {string}
     * @memberof Puja
     */
    idPuja: string;
    /**
     * 
     * @type {number}
     * @memberof Puja
     */
    cantidad: number;
    /**
     * 
     * @type {string}
     * @memberof Puja
     */
    pujador: string;
    /**
     * 
     * @type {string}
     * @memberof Puja
     */
    producto: string;
    /**
     * 
     * @type {string}
     * @memberof Puja
     */
    fechaPuja: string;
}

/**
 * Check if a given object implements the Puja interface.
 */
export function instanceOfPuja(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "idPuja" in value;
    isInstance = isInstance && "cantidad" in value;
    isInstance = isInstance && "pujador" in value;
    isInstance = isInstance && "producto" in value;
    isInstance = isInstance && "fechaPuja" in value;

    return isInstance;
}

export function PujaFromJSON(json: any): Puja {
    return PujaFromJSONTyped(json, false);
}

export function PujaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Puja {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idPuja': json['idPuja'],
        'cantidad': json['cantidad'],
        'pujador': json['pujador'],
        'producto': json['producto'],
        'fechaPuja': json['fecha_puja'],
    };
}

export function PujaToJSON(value?: Puja | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idPuja': value.idPuja,
        'cantidad': value.cantidad,
        'pujador': value.pujador,
        'producto': value.producto,
        'fecha_puja': value.fechaPuja,
    };
}

