/* tslint:disable */
/* eslint-disable */
/**
 * Jesus Antona
 * Ingeniería Web
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsuarioCreate
 */
export interface UsuarioCreate {
    /**
     * 
     * @type {string}
     * @memberof UsuarioCreate
     */
    usuario: string;
    /**
     * 
     * @type {string}
     * @memberof UsuarioCreate
     */
    nombre: string;
    /**
     * 
     * @type {string}
     * @memberof UsuarioCreate
     */
    apellido1: string;
    /**
     * 
     * @type {string}
     * @memberof UsuarioCreate
     */
    apellido2?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UsuarioCreate
     */
    valoracion: number;
    /**
     * 
     * @type {boolean}
     * @memberof UsuarioCreate
     */
    esAdmin: boolean;
}

/**
 * Check if a given object implements the UsuarioCreate interface.
 */
export function instanceOfUsuarioCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "usuario" in value;
    isInstance = isInstance && "nombre" in value;
    isInstance = isInstance && "apellido1" in value;
    isInstance = isInstance && "valoracion" in value;
    isInstance = isInstance && "esAdmin" in value;

    return isInstance;
}

export function UsuarioCreateFromJSON(json: any): UsuarioCreate {
    return UsuarioCreateFromJSONTyped(json, false);
}

export function UsuarioCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsuarioCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'usuario': json['usuario'],
        'nombre': json['nombre'],
        'apellido1': json['apellido1'],
        'apellido2': !exists(json, 'apellido2') ? undefined : json['apellido2'],
        'valoracion': json['valoracion'],
        'esAdmin': json['esAdmin'],
    };
}

export function UsuarioCreateToJSON(value?: UsuarioCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'usuario': value.usuario,
        'nombre': value.nombre,
        'apellido1': value.apellido1,
        'apellido2': value.apellido2,
        'valoracion': value.valoracion,
        'esAdmin': value.esAdmin,
    };
}

